### ISSUE TITLE
Crux not installing in cydia 

### ISSUE THREAD

**Issue by anglim3** [MPG13/FlashBackBugReports#4]
Crux is a dependency of Flashback, and it will not show up in Sileo. I have the creature survive repo but it is not there.

**Comment by anglim3** [comment]
Lol I put cydia in the title but I use Sileo

**Comment by MPG13** [comment]
The repo you have added is creaturesurvive.github.io? This is more an issue with CreatureSurvive’s repo, not an issue with FlashBack. Make sure you’ve refreshed your sources.
