### ISSUE TITLE
Settings app freeze and crash 

### ISSUE THREAD

**Issue by Iamapower** [MPG13/FlashBackBugReports#5]
After snapping back to my saved snapshots some times the Setting app freezes and I can’t get it back till I snap back to any other snapshot.

**Comment by MPG13** [comment]
Are you mistaking FlashBack for SnapBack? They are two different apps, and FlashBack has backups and restores, no snapshots or snapping back.

**Comment by Iamapower** [comment]
Yes you are right I’m really sorry will delete it.
